name: Build and Check Nodejs project

on: 
 push:
  branches:
      - master


jobs:
    Check-code-lint:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout self
            uses: actions/checkout@v3
          - name: Run Dev Lint
            run: docker compose run dev npm run lint:check

    Check-Format-Check:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout self
          uses: actions/checkout@v3
        - name: Run Dev Format
          run: docker compose run dev npm run format:check

    Run-Test-Cases:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Self
          uses: actions/checkout@v3
        - name: Run Test case
          run: docker compose run dev npm run test

    Build-PushImage:
      needs: [ Check-code-lint, Check-Format-Check, Run-Test-Cases ]
      runs-on: ubuntu-latest
      outputs:
        sha_short: ${{steps.vars.outputs.sha_short}}
      steps:
        - name: Checkout self
          uses: actions/checkout@v3
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      
        - name: Get short commit hash
          id: vars
          run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

        - name: Build and push with commit hash tag
          run: |
            docker compose build prod
            docker tag ci-cd-pipeline-prod ashokgani6300/cicd-app:${{ steps.vars.outputs.sha_short }}
            docker push ashokgani6300/cicd-app:${{ steps.vars.outputs.sha_short }}
  
        
